[package]
name            = "buncher"
version         = "0.2.2"
edition         = "2021"
authors         = [ "Miezhiko" ]
repository      = "https://github.com/Miezhiko/buncher"
license         = "AGPL-3.0-only"
readme          = "Readme.md"

[dependencies]
image           = { version = "0.24.2", features = [ "png", "jpeg", "tiff" ] }
anyhow          = "1"
clap            = { version = "3.1", features = ["derive", "color"] }
globwalk        = "0.8"
generic-array   = "0.14"
typenum         = "1.15"
sha3            = "0.10"
tokio           = { version = "1.18.1", features = ["rt-multi-thread", "time", "rt", "macros"] }
async-fs        = "1.5"
