[package]
name            = "buncher"
version         = "0.0.8"
edition         = "2021"
authors         = [ "Miezhiko" ]
repository      = "https://github.com/Miezhiko/buncher"
license         = "AGPL-3.0-only"
readme          = "Readme.md"

[dependencies]
image   = { version = "0.24", features = [ "png", "jpeg", "tiff" ] }
anyhow  = "1"
clap    = { version = "3.1", features = ["derive", "color"] }
glob    = "0.3"
sha3    = "0.10"
