[package]
name            = "buncher"
version         = "0.3.7"
edition         = "2021"
authors         = [ "Miezhiko" ]
repository      = "https://github.com/Miezhiko/buncher"
license         = "AGPL-3.0-only"
readme          = "Readme.md"

[dependencies]
anyhow          = "1.0"
globwalk        = "0.8"
generic-array   = "0.14"
typenum         = "1.16"
sha3            = "0.10"
async-fs        = "1.6"
indicatif       = "0.17"

[dependencies.clap]
version = "4"
features = ["derive", "color"]

[dependencies.tokio]
version = "1.24"
features = ["rt-multi-thread", "time", "rt", "macros"]

[dependencies.image]
git = "https://github.com/image-rs/image.git"
branch = "master"
features = [ "png", "jpeg", "tiff", "webp" ]

[profile.release]
opt-level = 3
overflow-checks = false
debug-assertions = false
lto = "fat"
